package com.core.entity;
// Generated 2018/9/11 �U�� 12:01:11 by Hibernate Tools 5.1.0.Alpha1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * MspConfig generated by hbm2java
 */
@Entity
@Table(name = "test", catalog = "test")
public class Test implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
	private int id;
	private String test;
	private String msg;

	public Test() {
	}

	public Test(int id) {
		this.id = id;
	}

	public Test(int id, String test, String msg) {
		this.id = id;
		this.test = test;
		this.msg = msg;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "test", length = 10)
	public String getTest() {
		return this.test;
	}

	public void setTest(String test) {
		this.test = test;
	}

	@Column(name = "msg")
	public String getMsg() {
		return this.msg;
	}

	public void setMsg(String msg) {
		this.msg = msg;
	}

}
